/** Schéma JSON strict — blueprint prompt App Store AppLAB (Cursor / Claude). */

export const APPLAB_MVP_PROMPT_JSON_SCHEMA = {
  type: "object",
  additionalProperties: false,
  properties: {
    app_working_name: { type: "string" },
    one_liner: { type: "string" },
    value_proposition: { type: "string" },
    screens: {
      type: "array",
      minItems: 8,
      maxItems: 14,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          id: { type: "string" },
          title: { type: "string" },
          purpose: { type: "string" },
          key_components: { type: "array", items: { type: "string" }, maxItems: 8 },
        },
        required: ["id", "title", "purpose", "key_components"],
      },
    },
    onboarding_steps: {
      type: "array",
      minItems: 3,
      maxItems: 6,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          step: { type: "number" },
          screen_id: { type: "string" },
          headline: { type: "string" },
          body: { type: "string" },
        },
        required: ["step", "screen_id", "headline", "body"],
      },
    },
    data_models: {
      type: "array",
      minItems: 2,
      maxItems: 8,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          name: { type: "string" },
          fields: { type: "array", items: { type: "string" }, maxItems: 12 },
          notes: { type: "string" },
        },
        required: ["name", "fields", "notes"],
      },
    },
    iap_model: { type: "string" },
    paywall_trigger: { type: "string" },
    iap_products: {
      type: "array",
      minItems: 1,
      maxItems: 4,
      items: {
        type: "object",
        additionalProperties: false,
        properties: {
          product_id: { type: "string" },
          type: { type: "string" },
          label: { type: "string" },
          description: { type: "string" },
        },
        required: ["product_id", "type", "label", "description"],
      },
    },
    analytics_events: { type: "array", items: { type: "string" }, maxItems: 16 },
    folder_structure: { type: "array", items: { type: "string" }, maxItems: 24 },
    coding_rules: { type: "array", items: { type: "string" }, maxItems: 16 },
    negative_prompts: { type: "array", items: { type: "string" }, maxItems: 16 },
    apple_compliance: { type: "array", items: { type: "string" }, maxItems: 12 },
    accessibility: { type: "array", items: { type: "string" }, maxItems: 10 },
    execution_phases: { type: "array", items: { type: "string" }, minItems: 6, maxItems: 12 },
    trackapp_resource_ids: { type: "array", items: { type: "string" }, maxItems: 12 },
  },
  required: [
    "app_working_name",
    "one_liner",
    "value_proposition",
    "screens",
    "onboarding_steps",
    "data_models",
    "iap_model",
    "paywall_trigger",
    "iap_products",
    "analytics_events",
    "folder_structure",
    "coding_rules",
    "negative_prompts",
    "apple_compliance",
    "accessibility",
    "execution_phases",
    "trackapp_resource_ids",
  ],
} as const;
